version: "3.5"

services:

  ###
  # Frontend
  ###
  traefik:
    image: traefik:v1.5.1-alpine
    command:
      - --api
      - --docker
      - --docker.watch
      - --docker.constraints=tag==web
      - --entryPoints=Name:http Address::80 Compress::true
      - --defaultEntryPoints=http
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /dev/null:/traefik.toml:rw
    ports:
      - "80:80"
      - "8080:8080"  # Traefik Frontend
      - "443:443"
    networks:
      - "stack"

  app:
    # image: asyncy/platform-app
    image: trinitronx/python-simplehttpserver
    labels:
      - "traefik.tags=web"
      - "traefik.backend=app"
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host: app.${DNS:-asyncy.net}"
    ports:
      - "8080"
    volumes:
      - ./mock/app:/var/www
    networks:
      - "stack"

  hub:
    # image: asyncy/platform-hub
    image: trinitronx/python-simplehttpserver
    labels:
      - "traefik.tags=web"
      - "traefik.backend=hub"
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host: hub.${DNS:-asyncy.net}"
    ports:
      - "8080"
    volumes:
      - ./mock/hub:/var/www
    networks:
      - "stack"

  bootstrap:
    # image: asyncy/platform-bootstrap
    image: trinitronx/python-simplehttpserver
    labels:
      - "traefik.tags=web"
      - "traefik.backend=bootstrap"
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host: ${DNS:-asyncy.net}"
    ports:
      - "8080"
    volumes:
      - ./mock/bootstrap:/var/www
    networks:
      - "stack"

  api-rest:
    # image: asyncy/platform-api-rest
    # command: server --public
    image: trinitronx/python-simplehttpserver
    labels:
      - "traefik.tags=web"
      - "traefik.backend=api-rest"
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host: api.${DNS:-asyncy.net}"
    ports:
      - "8080"
    volumes:
      - ./mock/api-rest:/var/www
    networks:
      - "stack"

  api-graphql:
    # image: asyncy/platform-api-graphql
    # command: server --public
    image: trinitronx/python-simplehttpserver
    labels:
      - "traefik.tags=web"
      - "traefik.backend=api-graphql"
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host: api.${DNS:-asyncy.net}; PathPrefix: /graphql"
    ports:
      - "8080"
    volumes:
      - ./mock/api-graphql:/var/www
    networks:
      - "stack"

  ###
  # Management
  ###
  metabase:
    image: metabase/metabase
    labels:
      - "traefik.tags=web"
      - "traefik.backend=metabase"
      - "traefik.port=3000"
      - "traefik.frontend.rule=Host: metabase.${DNS:-asyncy.net}"
    ports:
      - "3000"
    volumes:
      - metabase-volume:/metabase-data
    networks:
      - "stack"

  ###
  # Backend
  ###
  api-private:
    # image: asyncy/platform-api-rest
    # command: server --private
    image: trinitronx/python-simplehttpserver
    ports:
      - "8080"
    volumes:
      - ./github.pem:/github.pem:ro
      - ./mock/api-private:/var/www
    depends_on:
      - postgres
    networks:
      - "stack"

  engine:
    image: asyncy/platform-engine
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
    environment:  # [TODO] remove if @jacoco set to default
      broker: amqp://rabbitmq:rabbitmq@rabbitmq:5672//
      database: postgres://postgres:@postgres:5432/postgres
      mongo: mongodb://mongo:27017
    depends_on:
      - api-private
      - rabbitmq
      - mongodb
    networks:
      - "stack"

  postgres:
    image: postgres:10.3-alpine
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    networks:
      - "stack"

  rabbitmq:
    image: rabbitmq:3.7.3-alpine
    volumes:
      - rabbitmq-volume:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
    networks:
      - "stack"

  mongodb:
    image: mongo:3.6.3
    command: mongod --smallfiles --logpath=/dev/null
    environment:
      # - MONGO_DATA_DIR=/data/db
      # - MONGO_LOG_DIR=/dev/null
      - MONGODB_USER=admin
      - MONGODB_PASS=admin
    volumes:
      - mongodb-volume:/data/db
    networks:
      - "stack"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000"
    labels:
      - "traefik.tags=web"
      - "traefik.backend=grafana"
      - "traefik.port=3000"
      - "traefik.frontend.rule=Host: grafana.${DNS:-asyncy.net}"
    networks:
      - "stack"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.1
    environment:
      - "http.host=0.0.0.0"
      - "transport.host=127.0.0.1"
      - "ELASTIC_PASSWORD=admin"
    ports:
      - "9200"
    volumes:
      - elasticsearch-volume:/usr/share/elasticsearch/data
    networks:
      - "stack"

  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.1
    container_name: kibana
    environment:
      - "ELASTICSEARCH_USERNAME=kibana"
      - "ELASTICSEARCH_PASSWORD=admin"
    ports:
      - "5601"
    labels:
      - "traefik.tags=web"
      - "traefik.backend=kibana"
      - "traefik.port=5601"
      - "traefik.frontend.rule=Host: kibana.${DNS:-asyncy.net}"
    networks:
      - "stack"

  # TODO: merge into bootstrap
  setup_kibana:
    image: centos:7
    environment:
      - "ELASTIC_PASSWORD=admin"
    depends_on:
      - elasticsearch
    volumes:
      - ./scripts/setup-kibana.sh:/usr/local/bin/setup-kibana.sh:ro
    command: ['/bin/bash', '-c', 'cat /usr/local/bin/setup-kibana.sh | tr -d "\r" | bash']
    networks:
      - "stack"

  fluentd:
    image: fluent/fluentd
    networks:
      - "stack"

volumes:
  postgres-volume:
  rabbitmq-volume:
  mongodb-volume:
  metabase-volume:
  elasticsearch-volume:

networks: {stack: {}}
